jmx-objs := jmx_main.o jmx_utils.o  regexp.o k_json.o  jmx_log.o jmx_client.o jmx_client_fs.o 
jmx-objs += jmx_conntrack.o  jmx_mac.o jmx_config.o jmx_mac_filter.o 
jmx-objs += jmx_app_filter.o
jmx-objs += jmx_v2_rules.o jmx_v2_nl_handler.o jmx_v2_ac.o
jmx-objs += jmx_v3_rules.o jmx_v3_nl_handler.o jmx_v3_ac.o
obj-m += jmx.o
