import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx={window:{},Date,Map,Set,AbortController,queueMicrotask};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../files/www/dreamingwrt/static/js/dwrt-data-registry.js',import.meta.url),'utf8'),ctx);
const registry=new ctx.window.DWRTDataRegistry({fetcher:async()=>({contract:'product-plane.v1',resource:'wifi.config',ok:true,data:{revision:2},capabilities:{save_config:false,reasons:{save_config:'executor_disabled'},read:{supported:true},apply:{supported:true,writable:false,reason:'read_only'}},permissions:{'wifi:write':false,read:true},entitlement:null,meta:{observed_at:123,stale:true}})});
registry.define('wifi.config',{url:'/wifi'});
const snap=await registry.request('wifi.config');
assert.equal(snap.status,'stale');assert.equal(snap.observed_at,123);assert.equal(snap.capabilities.save_config,false);
assert.equal(registry.hasCapability('wifi.config','save_config'),false);assert.equal(registry.hasCapability('wifi.config','read'),true);assert.equal(registry.hasCapability('wifi.config','apply'),false);
assert.equal(registry.hasPermission('wifi.config','wifi:write'),false);assert.equal(registry.hasPermission('wifi.config','wifi:read'),true);
assert.equal(registry.access('wifi.config',{permission:'wifi:write'}).state,'forbidden');
const el={setAttribute(k,v){this[k]=v;}};const stop=registry.bindControl('wifi.config',el,{capability:'save_config'});assert.equal(el.disabled,true);assert.equal(el.title,'executor_disabled');
registry.accept('wifi.config',{data:{revision:3}});assert.equal(el.disabled,false);assert.equal(registry.hasCapability('wifi.config','future_capability'),true);assert.equal(registry.hasPermission('wifi.config','wifi:write'),true);stop();
registry.accept('enterprise.catalog',{contract:'product-plane.v1',data:[],entitlement:{required:true,valid:false,reason:'license_required'}});
registry.accept('network.wans',{data:[]});
assert.equal(registry.access('enterprise.catalog').allowed,false);assert.equal(registry.access('network.wans').allowed,true);
registry.accept('wifi.config',{contract:'product-plane.v1',data:{},capabilities:{save_config:false}},{cacheKey:'device-b'});
assert.equal(registry.hasCapability('wifi.config','save_config',{cacheKey:'device-b'}),false);assert.equal(registry.hasCapability('wifi.config','save_config'),true);
console.log('product-plane registry: envelope/legacy, scoped capabilities/permissions/entitlement, cache variants and bound control passed');
