import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const context={window:{},Date,Map,Set};vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('../files/www/dreamingwrt/static/js/task-center.js',import.meta.url),'utf8'),context);
let now=200000000;const store=new context.window.DWRTTaskCenterStore(()=>now);
const ota={key:'ota.task',label:'OTA'},wifi={key:'wifi.task',label:'Wi-Fi 配置'};
store.accept(ota,{data:{task_id:'ota-1',state:'in_progress',progress:40,started_at:100000}});
store.accept(wifi,{data:{tasks:[{task_id:'new-done',state:'success',started_at:190000,updated_at:199000},{task_id:'new-active',state:'pending',started_at:150000},{task_id:'old-failed',state:'failed',started_at:90000,completed_at:100000}]}});
assert.deepEqual(Array.from(store.list(),x=>x.id),['new-active','ota-1','new-done']);
assert.equal(store.list()[1].progress,40);assert.equal(store.list()[0].progress,null);
store.accept(ota,{data:{task_id:'ota-1',state:'success',progress:100,started_at:100000,updated_at:200000}});
store.accept(ota,{data:{task_id:'ota-2',state:'pending',started_at:200001}});
assert.equal(store.list().find(x=>x.id==='ota-1').stale,true,'completed task retained after next task starts');
store.fail(wifi,new Error('source_unavailable'));assert.equal(store.list().find(x=>x.id==='new-active').stale,true);
store.accept(ota,{data:{task_id:'idle',state:'idle',started_at:0}});assert.equal(store.list().some(x=>x.id==='idle'),false);
store.accept(ota,{data:{task_id:'no-terminal-time',state:'success',started_at:100000}});
now+=86400001;assert.equal(store.list().length,0);
store.accept(ota,{data:{task_id:'no-terminal-time',state:'success',started_at:100000}});assert.equal(store.list().length,0,'poll must not resurrect an expired terminal task');
console.log('TaskCenter: real endpoint shapes, active/time ordering, unknown progress, completion retention, source failure and 24h expiry passed');
