// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef DREAMINGOS_CLOUD_TRANSFER_H
#define DREAMINGOS_CLOUD_TRANSFER_H
#define CW_FEATURE_STREAM 1u
#define CW_FEATURE_WEBSOCKET 2u
#define CW_FEATURES_V1 (CW_FEATURE_STREAM | CW_FEATURE_WEBSOCKET)
#define CW_LEGACY_UPLOAD 262144u
#define CW_LEGACY_RESPONSE 8388608u
#define CW_TRANSFER_MAX 1073741824u
#endif
