// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Standalone checks for topology_grubenv_format_valid().
 *
 * The function is static inside otad_topology.c, so the logic under test is
 * kept here verbatim; keep the two in sync when either changes.
 *
 * This exists because the original validator declared a stock grubenv
 * malformed: it read the "# WARNING: Do not edit this file..." comment that
 * grub-editenv writes after the header as the start of the '#' padding run,
 * failed the whole block, and left rollback_enabled permanently false with
 * reason bootloader_grubenv_invalid on a healthy A/B system.
 *
 * The reject cases matter as much as the accept ones: the fix must not buy
 * compatibility by loosening the padding check, since data hidden behind
 * apparent padding is the hazard that check exists for.
 *
 *   cc -O1 -Wall -Wextra -o /tmp/grubenv_fixture \
 *       tests/otad_grubenv_format_fixture.c && /tmp/grubenv_fixture
 */
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#define OTAD_TOPOLOGY_GRUBENV_SIZE 1024U
#define OTAD_TOPOLOGY_GRUBENV_HEADER "# GRUB Environment Block\n"

/* verbatim copy of the patched function */
static int topology_grubenv_format_valid(const char *text)
{
    const char *body;
    const char *line;
    const char *end;
    size_t header_len = strlen(OTAD_TOPOLOGY_GRUBENV_HEADER);
    int seen_assignment = 0;

    if (!text || strlen(text) != OTAD_TOPOLOGY_GRUBENV_SIZE ||
        strncmp(text, OTAD_TOPOLOGY_GRUBENV_HEADER, header_len))
        return -1;
    body = text + header_len;
    while (*body) {
        const char *equals;
        const char *p;

        if (*body == '#') {
            /*
             * Two different things start with '#', and conflating them declared
             * the bootloader's own environment malformed: the trailing '#'
             * padding that fills the block, and the leading comment lines
             * grub-editenv writes. A stock file carries
             * "# WARNING: Do not edit this file by tools other than
             * grub-editenv!!!" right after the header. Reading that as the start
             * of padding failed the whole file and left rollback permanently
             * disabled on a healthy system.
             *
             * The layout is header, then comments, then assignments, then
             * padding to the end. So a comment is only accepted before the first
             * assignment, and padding must run unbroken to the end of the block.
             * Allowing a comment anywhere would reopen the real hazard here,
             * which is data hidden behind what looks like padding.
             */
            for (p = body; *p == '#'; p++)
                ;
            if (!*p)
                return seen_assignment ? 0 : -1;
            if (seen_assignment)
                return -1;
            end = strchr(body, '\n');
            if (!end)
                return -1;
            for (p = body; p < end; p++) {
                if ((unsigned char)*p < 0x20 || (unsigned char)*p > 0x7e)
                    return -1;
            }
            body = end + 1;
            continue;
        }
        line = body;
        end = strchr(line, '\n');
        if (!end || end == line)
            return -1;
        equals = memchr(line, '=', (size_t)(end - line));
        if (!equals || equals == line ||
            (!isalpha((unsigned char)line[0]) && line[0] != '_'))
            return -1;
        for (p = line + 1; p < equals; p++) {
            if (!isalnum((unsigned char)*p) && *p != '_')
                return -1;
        }
        for (p = equals + 1; p < end; p++) {
            if ((unsigned char)*p < 0x20 || (unsigned char)*p > 0x7e)
                return -1;
        }
        seen_assignment = 1;
        body = end + 1;
    }
    return -1;
}

static char *mk(const char *content) {
    static char buf[OTAD_TOPOLOGY_GRUBENV_SIZE + 1];
    size_t n = strlen(content);
    if (n > OTAD_TOPOLOGY_GRUBENV_SIZE) { fprintf(stderr, "too long\n"); exit(2); }
    memcpy(buf, content, n);
    memset(buf + n, '#', OTAD_TOPOLOGY_GRUBENV_SIZE - n);
    buf[OTAD_TOPOLOGY_GRUBENV_SIZE] = '\0';
    return buf;
}

static int fails = 0;
static void check(const char *name, const char *text, int want) {
    int got = topology_grubenv_format_valid(text);
    int ok = (want == 0) ? (got == 0) : (got != 0);
    if (!ok) fails++;
    printf("%-58s want=%-8s got=%-3d %s\n", name,
           want == 0 ? "accept" : "reject", got, ok ? "PASS" : "FAIL");
}

int main(void) {
    /* the real 30.1 file shape: header + stock WARNING comment + kv pairs */
    check("real grubenv (header + WARNING comment + kv)",
        mk("# GRUB Environment Block\n"
           "# WARNING: Do not edit this file by tools other than grub-editenv!!!\n"
           "active_slot=A\npending_slot=\ntries_left=0\nlast_good_slot=A\n"
           "slot_a_valid=1\nslot_b_valid=1\n"), 0);

    /* no comment at all, pure kv then padding: must still work */
    check("no comment line, kv then padding",
        mk("# GRUB Environment Block\nactive_slot=A\n"), 0);

    /* multiple consecutive comment lines */
    check("two comment lines then kv",
        mk("# GRUB Environment Block\n# one\n# two\nactive_slot=A\n"), 0);

    /* A comment after assignments is rejected on purpose: grub-editenv does not
     * emit one, and accepting it anywhere would let data hide behind something
     * that looks like padding. */
    check("comment after kv is rejected (by design)",
        mk("# GRUB Environment Block\nactive_slot=A\n# note\npending_slot=\n"), -1);

    /* ---- the strictness that must NOT be lost ---- */

    /* data hidden after padding started: reject */
    {
        static char buf[OTAD_TOPOLOGY_GRUBENV_SIZE + 1];
        const char *head = "# GRUB Environment Block\nactive_slot=A\n";
        size_t n = strlen(head);
        memcpy(buf, head, n);
        memset(buf + n, '#', OTAD_TOPOLOGY_GRUBENV_SIZE - n);
        /* bury a kv pair deep inside the padding run */
        memcpy(buf + 600, "\nevil_slot=B\n", 13);
        buf[OTAD_TOPOLOGY_GRUBENV_SIZE] = '\0';
        check("data buried inside padding run", buf, -1);
    }

    /* padding run that does not reach the end, followed by junk on same line */
    check("hash run then junk on the same line",
        mk("# GRUB Environment Block\nactive_slot=A\n####evil\n"), -1);

    /* wrong size */
    check("short file", "# GRUB Environment Block\nactive_slot=A\n", -1);

    /* bad header */
    check("bad header", mk("# NOT GRUB\nactive_slot=A\n"), -1);

    /* malformed kv: no equals */
    check("kv without equals", mk("# GRUB Environment Block\nactive_slot\n"), -1);

    /* malformed kv: key starts with a digit */
    check("key starts with digit", mk("# GRUB Environment Block\n9slot=A\n"), -1);

    /* non-printable inside a comment line must be rejected */
    check("control char inside comment line",
        mk("# GRUB Environment Block\n# bad\x01comment\nactive_slot=A\n"), -1);

    /* unterminated final kv line (no trailing newline before padding) */
    check("kv line not newline-terminated",
        mk("# GRUB Environment Block\nactive_slot=A"), -1);

    printf("\n%s  (%d failure%s)\n", fails ? "SOME TESTS FAILED" : "ALL TESTS PASSED",
           fails, fails == 1 ? "" : "s");
    return fails ? 1 : 0;
}
