#!/usr/bin/env python3
"""Exercise runtime publication and app guard/migration using isolated real files."""
from pathlib import Path
import json
import os
import signal
import subprocess
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]


def main():
    flags = subprocess.check_output(
        ['pkg-config', '--cflags', '--libs', 'json-c', 'libcurl', 'openssl', 'zlib'],
        text=True).split()
    with tempfile.TemporaryDirectory(prefix='memory-runtime-') as tmp:
        root = Path(tmp)
        run, data, init = [root / name for name in ('run', 'data', 'init')]
        for path in (run, data / 'apps', init):
            path.mkdir(parents=True)
        defines = [f'-DDW_MP_RUN_DIR="{run}"', f'-DDATA_ROOT="{data}"',
                   f'-DINITD_DIR="{init}"', f'-DAPPSTORE_ROOT="{root / "registry"}"']
        worker = root / 'worker'
        subprocess.run(['cc', '-std=c11', '-D_GNU_SOURCE', '-O1', *defines,
                        str(ROOT / 'tools/appstore/worker/dwrt-appstore-worker.c'),
                        str(ROOT / 'src/system/memory_profile.c'), *flags,
                        '-o', str(worker)], check=True)

        def profile(mode):
            (run / 'memory-profile.json').write_text(json.dumps({
                'requested_mode': mode, 'config_revision': 1}))

        manifest = root / 'manifest.json'
        manifest.write_text('{}')
        profile('compact')
        result = subprocess.run([worker, '--run-guard', manifest, '/bin/true'],
                                capture_output=True, text=True)
        assert result.returncode == 75 and 'resource_peak_unknown' in result.stderr, result
        profile('standard')
        assert subprocess.run([worker, '--run-guard', manifest, '/bin/true']).returncode == 0
        manifest.write_text(json.dumps({'requires': {'minMemoryBytes': 2**60}}))
        result = subprocess.run([worker, '--run-guard', manifest, '/bin/true'],
                                capture_output=True, text=True)
        assert result.returncode == 75 and 'insufficient_memory' in result.stderr, result
        profile('compact')
        manifest.write_text(json.dumps({'requires': {'incrementalPeakBytes': {'start': 0}}}))
        parent = subprocess.Popen([worker, '--run-guard', manifest, '/bin/sleep', '30'])
        child = None
        try:
            for _ in range(100):
                children = Path(f'/proc/{parent.pid}/task/{parent.pid}/children')
                if children.exists() and children.read_text().strip():
                    child = int(children.read_text().split()[0])
                    break
                time.sleep(.01)
            assert child is not None, 'guard did not start child'
            parent.send_signal(signal.SIGTERM)
            assert parent.wait(timeout=5) == 128 + signal.SIGTERM
            assert not Path(f'/proc/{child}').exists(), 'guard left child running'
        finally:
            if parent.poll() is None:
                parent.kill()
                parent.wait()
        assert subprocess.run([worker, '--run-guard', manifest, '/bin/true']).returncode == 0
        print('guard: unknown peak/minimum refused, standard preserved, signal forwarded, lease released: PASS')

        generated = '#!/bin/sh\n# DreamingOS App Store service (generated by dwrt-appstore-worker) app=sample\n'
        for app in ('sample', 'custom'):
            current = data / 'apps' / app / 'current'
            current.mkdir(parents=True)
            (current / 'manifest.json').write_text(json.dumps({'service': {
                'executable': 'payload/app', 'args': ['${DATA}', "a'b"], 'autostart': False}}))
        unit = init / 'dreamingos-app-sample'
        custom = init / 'dreamingos-app-custom'
        unit.write_text(generated)
        custom.write_text('#!/bin/sh\n# custom service\n')
        backup = root / 'backup'
        result = subprocess.run([worker, '--migrate-start-guards', backup], capture_output=True)
        assert result.returncode == 1, 'custom unit must be reported'
        assert '--run-guard' in unit.read_text()
        assert "a'\\''b" in unit.read_text()
        assert (backup / unit.name).read_text() == generated
        assert custom.read_text() == '#!/bin/sh\n# custom service\n'
        first = unit.read_bytes()
        subprocess.run([worker, '--migrate-start-guards', backup], capture_output=True)
        assert unit.read_bytes() == first and (backup / unit.name).read_text() == generated
        print('migration: generated unit guarded, first backup retained, custom unit untouched, repeat safe: PASS')

        source = root / 'publish.c'
        source.write_text(r'''
#include <assert.h>
#include <string.h>
#include "system/memory_profile.h"
int main(void) {
    struct dw_memory_profile newer, older, loaded;
    assert(dw_mp_select("compact", "", 512 * DW_MP_MIB, &newer) == 0);
    assert(dw_mp_select("standard", "", 512 * DW_MP_MIB, &older) == 0);
    newer.revision = 3; older.revision = 2;
    assert(dw_mp_publish(&newer) == 0);
    assert(dw_mp_publish(&older) == 0);
    dw_mp_load(&loaded);
    assert(loaded.revision == 3 && !strcmp(loaded.requested, "compact"));
    newer.revision = 4;
    assert(dw_mp_publish(&newer) == 0);
    dw_mp_load(&loaded); assert(loaded.revision == 4);
    return 0;
}
''')
        test = root / 'publish'
        subprocess.run(['cc', '-std=c11', '-D_GNU_SOURCE', '-O1', *defines,
                        '-I' + str(ROOT / 'src'), str(source),
                        str(ROOT / 'src/system/memory_profile.c'), *flags, '-o', str(test)], check=True)
        subprocess.run([test], check=True)
        print('publication: older committed revision cannot replace newer runtime mode: PASS')


if __name__ == '__main__':
    main()
