#!/usr/bin/env python3
"""The stored traffic-log scope actually filters writes.

Acceptance item 4 asks for evidence that choosing `blocked` records only hits
that were enforced. A schema check cannot show that: the setting was storable
and readable long before anything consulted it. So this drives the real decision
functions.

`aegisxd_action_is_block()` and `aegisxd_hits_scope_admits()` are lifted out of
`aegisxd_hits.c` **by text** into a header the C fixture includes. Copying them
into the test would validate the copy: a regression in production could leave
this green. Extraction means the logic under test is the shipped logic, and a
rename or a changed condition breaks here instead of passing quietly.

The fixture links no ubus, curl or sqlite, so the gate runs in isolation;
`aegisxd_scope_refresh()` is stubbed and the cache is set per case.

A second check walks the producers: every function that inserts a hit must pass
through the gate. That is what catches a *sixth* producer being added later
without one, which is how a filter silently stops covering part of the log.
"""

from __future__ import annotations

from pathlib import Path
import re
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[1]
HITS_C = ROOT / "src/aegisxd/aegisxd_hits.c"
FIXTURE = ROOT / "tests/aegis_scope_gate_fixture.c"

HITS_SOURCE = HITS_C.read_text(encoding="utf-8")

# The five functions that insert into aegis_hits, and the source class each one
# must declare. Listed explicitly so a new producer has to be acknowledged here
# rather than inheriting coverage it does not have.
PRODUCERS = (
    ("aegisxd_hits_insert_dns_event", "AEGISXD_HIT_SOURCE_GATEWAY_DNS"),
    ("aegisxd_hits_insert_nft_counter_delta", "AEGISXD_HIT_SOURCE_AEGISX_SERVICE"),
    ("aegisxd_hits_insert_reputation_flow", "AEGISXD_HIT_SOURCE_AEGISX_SERVICE"),
    ("aegisxd_hits_insert_suricata_event_ex", "AEGISXD_HIT_SOURCE_AEGISX_SERVICE"),
    ("aegisxd_policy_insert_event", "AEGISXD_HIT_SOURCE_DEVICE_ADMIN"),
)


def function_body(name: str) -> str:
    """Return one function's text, brace-balanced, from the C source."""
    match = re.search(rf"^static\s[\w \t*]*\b{re.escape(name)}\(", HITS_SOURCE,
                      re.MULTILINE)
    assert match, f"{name}() not found in {HITS_C.name}; it was renamed or removed"
    start = match.start()
    depth = 0
    for index in range(HITS_SOURCE.index("{", start), len(HITS_SOURCE)):
        char = HITS_SOURCE[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return HITS_SOURCE[start:index + 1] + "\n"
    raise AssertionError(f"unbalanced braces while reading {name}()")


def write_extracted_header(directory: Path) -> Path:
    header = directory / "aegis_scope_gate_extracted.h"
    header.write_text(
        "/* Generated by test_aegis_scope_gate_runtime.py -- do not edit.\n"
        " * Lifted verbatim from src/aegisxd/aegisxd_hits.c. */\n"
        + function_body("aegisxd_action_is_block")
        + "\n"
        + function_body("aegisxd_hits_scope_admits"),
        encoding="utf-8")
    return header


def build_and_run(directory: Path) -> str:
    write_extracted_header(directory)
    binary = directory / "aegis-scope-gate-fixture"
    subprocess.run(
        ["cc", "-std=c11", "-Wall", "-Wextra", f"-I{directory}",
         str(FIXTURE), "-o", str(binary)],
        check=True, capture_output=True, text=True)
    result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert result.returncode == 0, (
        f"scope gate fixture failed:\n{result.stdout}{result.stderr}")
    return result.stdout


def test_gate_decisions_match_the_contract() -> None:
    with tempfile.TemporaryDirectory(prefix="aegis-scope-gate-") as raw:
        stdout = build_and_run(Path(raw))
    assert "ok: scope gate keeps enforced verdicts" in stdout, stdout


def test_every_producer_passes_through_the_gate() -> None:
    """A producer that skips the gate is a hole in the filter, not a style slip."""
    for function, source_enum in PRODUCERS:
        body = function_body(function)
        assert "aegisxd_hits_scope_admits(" in body, (
            f"{function}() inserts a hit without consulting "
            f"aegisxd_hits_scope_admits(); the stored scope would not filter it")
        assert source_enum in body, (
            f"{function}() does not classify itself as {source_enum}, so the "
            f"matching source toggle cannot switch it off")


def test_the_gate_fails_open_on_a_settings_read_error() -> None:
    """A storage hiccup must not silently blank the security log."""
    start = HITS_SOURCE.index("static void aegisxd_scope_refresh(")
    end = HITS_SOURCE.index("static int aegisxd_action_is_block(", start)
    body = HITS_SOURCE[start:end]
    failure = body.index("aegisxd_settings_load(&settings) != 0")
    tail = body[failure:body.index("} else {", failure)]
    assert "g_scope_cache.blocked_only = 0;" in tail, (
        "on a settings read failure the gate does not reset blocked_only, so a "
        "failed query could drop events instead of keeping them")
    for source in ("gateway_dns", "aegisx_service", "device_admin"):
        assert f"g_scope_cache.{source} = 1;" in tail, (
            f"{source} is not forced on when the settings read fails")


if __name__ == "__main__":
    test_gate_decisions_match_the_contract()
    test_every_producer_passes_through_the_gate()
    test_the_gate_fails_open_on_a_settings_read_error()
    print("ok: the stored scope filters writes, all five producers consult the "
          "gate, and a settings read error fails open")
