// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef __DREAMINGWRT_AI_LOCAL_RPC_PROTOCOL_H__
#define __DREAMINGWRT_AI_LOCAL_RPC_PROTOCOL_H__

#define DREAMINGWRT_AI_LOCAL_SOCKET "/var/run/dreamingwrt-ai.sock"
#define DREAMINGWRT_AI_LOCAL_REQUEST_MAX (128U * 1024U)
#define DREAMINGWRT_AI_LOCAL_RESPONSE_MAX (1024U * 1024U)
#define DREAMINGWRT_AI_LOCAL_DEFAULT_TIMEOUT_MS 240000

#endif
